packaging_format = 2

id = "converse"
name = "Converse"
description.en = "Web-based XMPP/Jabber chat client"
description.fr = "Client de chat XMPP/Jabber basé sur le Web"

version = "10.1.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MPL-2.0"
website = "http://conversejs.org"
demo = "https://inverse.chat/"
admindoc = "https://conversejs.org/docs/html/index.html"
code = "https://github.com/conversejs/converse.js"

[integration]
yunohost = ">= 11.0.9"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/converse"

    [install.init_main_permission]
    help.en = "If enabled, Converse will be accessible by people who doesn’t have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Converse sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
