packaging_format = 2

id = "converse"
name = "Converse"
description.en = "Web-based XMPP/Jabber chat client"
description.fr = "Client de chat XMPP/Jabber basé sur le Web"

version = "10.1.7~ynh2"

maintainers = []

[upstream]
license = "MPL-2.0"
website = "http://conversejs.org"
demo = "https://inverse.chat/"
admindoc = "https://conversejs.org/docs/html/index.html"
code = "https://github.com/conversejs/converse.js"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/converse"

    [install.init_main_permission]
    help.en = "If enabled, Converse will be accessible by people who doesn’t have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Converse sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/conversejs/converse.js/releases/download/v10.1.7/converse.js-10.1.7.tgz"
    sha256 = "9a44510c85b5628e037a9ce2fa838e5f1f90a55a80c1dbf6a36c1450fcad5388"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
