#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

    more_set_headers "Access-Control-Allow-Origin: *";
    
    # Path to source
    alias __INSTALL_DIR__/;

    index index.html;
}

location = __PATH__/http-bind {
    proxy_pass "http://localhost:5290/http-bind";
    include    proxy_params_no_auth;
}
