#!/bin/bash

source /usr/share/yunohost/helpers

# Stop script if errors
#REMOVEME? ynh_abort_if_errors

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
