#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If maindomain doesn't exist, create it
ynh_app_setting_set_default --key=maindomain --value=$(yunohost domain main-domain --output-as plain)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

ynh_config_add --template="index.html" --destination="$install_dir/index.html"
cp "../conf/libsignal-protocol.min.js" "$install_dir/dist/libsignal-protocol.min.js"

chmod -R 750 "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
